//
//  Created by CocoaPods on TODAYS_DATE.
//  Copyright (c) 2014 PROJECT_OWNER. All rights reserved.
//

#import "LCSymbol.h"

const struct LCSymbol LCSymbol = {
        .Banknote = @"banknote",
        .Bubble = @"bubble",
        .Bulb = @"bulb",
        .Calendar = @"calendar",
        .Camera = @"camera",
        .Clip = @"clip",
        .Clock = @"clock",
        .Cloud = @"cloud",
        .Cup = @"cup",
        .Data = @"data",
        .Diamond = @"diamond",
        .Display = @"display",
        .Eye = @"eye",
        .Fire = @"fire",
        .Food = @"food",
        .Heart = @"heart",
        .Key = @"key",
        .Lab = @"lab",
        .Like = @"like",
        .Location = @"location",
        .Lock = @"lock",
        .Mail = @"mail",
        .Megaphone = @"megaphone",
        .Music = @"music",
        .News = @"news",
        .Note = @"note",
        .Paperplane = @"paperplane",
        .Params = @"params",
        .Pen = @"pen",
        .Phone = @"phone",
        .Photo = @"photo",
        .Search = @"search",
        .Settings = @"settings",
        .Shop = @"shop",
        .Sound = @"sound",
        .Stack = @"stack",
        .Star = @"star",
        .Study = @"study",
        .TShirt = @"t-shirt",
        .Tag = @"tag",
        .Television = @"television",
        .Trash = @"trash",
        .Truck = @"truck",
        .User = @"user",
        .Vallet = @"vallet",
        .Video = @"video",
        .Vynil = @"vynil",
        .World = @"world",
};
